### ISSUE TITLE
Answer Set Solving in Practice (Tutorial) Videos

### ISSUE THREAD

**Issue by dudaka** [potassco/potassco.github.io#29]
Hi, 

I cannot watch the videos of Answer Set Solving in Practice (Tutorial) (https://potassco.org/doc/videos/2016/09/20/answer-set-solving-in-practice.html)
These videos are hosted on TechTalks.tv, and I cannot play any videos on this sides.
Even through I have tried changing another browsers, installing Adobe Flash Plugin, ...

Would you like to help me to watch those videos? If possible, please update the links or send me those videos to my email.

I am appropriated and looking forward to your response.

Best regards,
Dung Ho

**Comment by rkaminsk** [comment]
Since this is old, maybe you rather check out our youtube channel: <https://www.youtube.com/c/Potassco-live/videos>. Torsten is uploading material for an online course at the moment. 

Also, maybe Torsten still has a copy of the old videos and can upload them on youtube, too? I cannot help you with your Flash problem and only confirm that I cannot play the videos on my system too.

**Comment by tortinator** [comment]
The problem is that we do neither own nor control these videos. Perhaps we should remove their urls from our site if they do not work any longer. But I'd like to wait until we have the web presentation up for the new course material.

**Comment by dudaka** [comment]
Thank you for your responses.
I am looking forward to the new course's videos from the Youtube channel
